version: '3.8'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "8076:3000"
    environment:
      DATABASE_URL: postgresql://umami_admin:prgadt-3DS@umami-db:5432/umami_prod
      DATABASE_TYPE: postgresql
      APP_SECRET: JcqHvaG3A2WsXAyfa6rql2c32PR8lWB/ouUz8AlOhtU=
    depends_on:
      umami-db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000/api/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
      - public
  umami-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami_prod
      POSTGRES_USER: umami_admin
      POSTGRES_PASSWORD: prgadt-3DS
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  umami-db-data:

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
